#!/bin/sh
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Just to make sure you can launch it from anywhere you like
cd /offline/path

FILE=/web/path/example.status
LOCK=/web/path/example.lock

export SERVERS="$(php getservers.php)"

date > status.new
# See the fping manpage to tweak these. Encouraged to make it finish within one minute
((fping $SERVERS -c 100 -p 500 -i 5 -q) 2>&1) >> status.new
date >> status.new

touch "$LOCK"
mv status.new "$FILE"
rm "$LOCK"
